### ISSUE TITLE
QBENCHMARK

### ISSUE THREAD

**Issue by aloisimattia** [KDAB/vscode-qttest#1]
Hi, just wanted to ask if QBENCHMARK macro is supported, since the test that i created with it isn't listed and runned

**Comment by iamsergio** [comment]
If you comment the QBENCHMARK, does it appear ? I doubt it's related and I think it will continue to not appear.

Is the slot private ? (it should)

Does this work for you https://github.com/KDAB/qttest-utils/tree/master/test/qt_test
testA has a benchmark

Which OS and which Qt version ?

**Comment by aloisimattia** [comment]
ok i see that sometimes the list isn't refreshed, but if i delete the  build folder and rebuild the list is updated, can you confirm this behaviour?
Anyway it is a private slot and im using WIN 11 with Qt 5.15.14 and as compiler msvc64

**Comment by iamsergio** [comment]
Ok , I can reproduce. The refresh button isn't adding/removing tests. Will check your 2nd question after.

**Comment by iamsergio** [comment]
Please install v1.0.0 of the extension.

If you press the refresh icon it will add/remove new tests. But make sure you build first, as the extension will query the test executables.
