### ISSUE TITLE
QTests are not found

### ISSUE THREAD

**Issue by mmerlo** [KDAB/vscode-qttest#2]
Qt version: Qt 6.7.0
Operating system: macos 13.6.6
Extension version: v1.1.0

QTests are not discovered in this sample project: https://github.com/mmerlo/test_discovery_issue

The error in the KDAB qtest output is:
`ERROR: discoverAllTestExecutables: No QtTest executables were found`

Note that the code in the sample project is based on [this code](https://github.com/KDABLabs/kdabtv/tree/master/Qt-Widgets-and-more/UnitTests). 

Any idea on what the issue may be?

**Comment by iamsergio** [comment]
Reproduced on Linux as well.
This happens because the extension runs ctest in the build directory, while that project has them inside Tests/.
Probably need to find all directories containing CTestTestfile.cmake

**Comment by iamsergio** [comment]
As a workaround, move the `enable_testing()` line, from `Tests/CMakeLists.txt`  to `CMakeLists.txt` before `add_subdirectory(Tests)`

**Comment by mmerlo** [comment]
Confirmed that the workaround fixes the issue.
